In [2]:
print("1. Cargamos Librerias")
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder,StandardScaler,PowerTransformer
from lightgbm import LGBMClassifier
from sklearn.pipeline import make_pipeline
from sklearn.compose import make_column_transformer
from sklearn.model_selection import KFold, cross_val_predict, train_test_split,GridSearchCV,cross_val_score
import bentoml

1. Cargamos Librerias


In [58]:
###DATA PROCESSING
import pickle 
print("2. Entrenando Modelo")
df = pd.read_csv('data/heart.csv')
numerical= df.drop(['HeartDisease'], axis=1).select_dtypes('number').columns
categorical = df.select_dtypes('object').columns
y = df['HeartDisease']
X= df.drop('HeartDisease', axis=1)
y= df['HeartDisease']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
ohe= OneHotEncoder()
ct= make_column_transformer((ohe,categorical),remainder='passthrough')  
pipe = make_pipeline(ct)
pipe.fit_transform(X_train)
X_train = pipe.transform(X_train)
# X_test = pipe.transform(X_test)
np.savetxt('heart_train_tf.csv', X_train, delimiter=',')
pickle.dump(pipe, open("processors/encoder.pkl", "wb"))


2. Entrenando Modelo


In [67]:
from numpy import loadtxt
X_train = np.loadtxt('heart_train_tf.csv', delimiter=',')
y_train = pd.read_csv('data/heart_train_y.csv')["HeartDisease"]
model=LGBMClassifier(random_state=0)
pipe = make_pipeline(model)
pipe.fit(X_train, y_train)


Pipeline(steps=[('lgbmclassifier', LGBMClassifier(random_state=0))])

In [68]:
y_pred = pipe.predict_proba(input_data)

In [69]:
y_pred

array([[9.87126398e-01, 1.28736024e-02],
       [2.24421330e-02, 9.77557867e-01],
       [1.39404621e-02, 9.86059538e-01],
       [6.88028578e-03, 9.93119714e-01],
       [9.48121581e-01, 5.18784188e-02],
       [5.35926939e-01, 4.64073061e-01],
       [9.29163302e-02, 9.07083670e-01],
       [8.37159015e-01, 1.62840985e-01],
       [7.44406044e-01, 2.55593956e-01],
       [3.49855566e-02, 9.65014443e-01],
       [5.36445024e-01, 4.63554976e-01],
       [9.82599687e-01, 1.74003131e-02],
       [1.62881648e-01, 8.37118352e-01],
       [9.87398877e-01, 1.26011228e-02],
       [1.66212859e-02, 9.83378714e-01],
       [3.17231407e-01, 6.82768593e-01],
       [9.77839557e-01, 2.21604430e-02],
       [1.41938893e-01, 8.58061107e-01],
       [2.21648958e-01, 7.78351042e-01],
       [7.82053426e-01, 2.17946574e-01],
       [5.89092836e-02, 9.41090716e-01],
       [1.03925381e-01, 8.96074619e-01],
       [9.98569457e-01, 1.43054344e-03],
       [7.09332378e-01, 2.90667622e-01],
       [7.742170

In [56]:
print("2. Train Test Split")
df = pd.read_csv('data/heart.csv')
numerical= df.drop(['HeartDisease'], axis=1).select_dtypes('number').columns
categorical = df.select_dtypes('object').columns
y = df['HeartDisease']
X= df.drop('HeartDisease', axis=1)
y= df['HeartDisease']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
y_train.to_csv('data/heart_train_y.csv',index=False)

2. Train Test Split


In [51]:
X_train

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
712   58   M           ASY        100          234          0     Normal   
477   61   M           ASY        110            0          1     Normal   
409   53   M           NAP        160            0          1        LVH   
448   63   M           ASY        160          230          1     Normal   
838   63   M           ASY        130          330          1        LVH   
..   ...  ..           ...        ...          ...        ...        ...   
106   48   F           ASY        120          254          0         ST   
270   45   M           ASY        120          225          0     Normal   
860   60   M           ASY        130          253          0     Normal   
435   60   M           ASY        152            0          0         ST   
102   40   F           ASY        150          392          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  
712    156              N      0.1       Up  
477    108              Y      2.0     Down  
409    122              Y      0.0     Flat  
448    105              Y      1.0     Flat  
838    132              Y      1.8       Up  
..     ...            ...      ...      ...  
106    110              N      0.0       Up  
270    140              N      0.0       Up  
860    144              Y      1.4       Up  
435    118              Y      0.0       Up  
102    130              N      2.0     Flat  

[642 rows x 11 columns]

In [46]:
encoder = pickle.load(open("processors/encoder.pkl", "rb"))
input_data = encoder.transform(X_test)

In [70]:
#######REAL TEST

In [73]:
    X_train = np.loadtxt('heart_train_tf.csv', delimiter=',')
    y_train = pd.read_csv('data/heart_train_y.csv')["HeartDisease"]
    model=LGBMClassifier(random_state=0)
    pipe = make_pipeline(model)
    pipe.fit(X_train, y_train)

Pipeline(steps=[('lgbmclassifier', LGBMClassifier(random_state=0))])

In [79]:
df = pd.read_csv('data/heart.csv')
numerical= df.drop(['HeartDisease'], axis=1).select_dtypes('number').columns
categorical = df.select_dtypes('object').columns
y = df['HeartDisease']
X= df.drop('HeartDisease', axis=1)
y= df['HeartDisease']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
encoder = pickle.load(open("processors/encoder.pkl", "rb"))
input_data = encoder.transform(X_test)

In [76]:
y_pred = pipe.predict_proba(input_data)
y_pred

array([[9.87126398e-01, 1.28736024e-02],
       [2.24421330e-02, 9.77557867e-01],
       [1.39404621e-02, 9.86059538e-01],
       [6.88028578e-03, 9.93119714e-01],
       [9.48121581e-01, 5.18784188e-02],
       [5.35926939e-01, 4.64073061e-01],
       [9.29163302e-02, 9.07083670e-01],
       [8.37159015e-01, 1.62840985e-01],
       [7.44406044e-01, 2.55593956e-01],
       [3.49855566e-02, 9.65014443e-01],
       [5.36445024e-01, 4.63554976e-01],
       [9.82599687e-01, 1.74003131e-02],
       [1.62881648e-01, 8.37118352e-01],
       [9.87398877e-01, 1.26011228e-02],
       [1.66212859e-02, 9.83378714e-01],
       [3.17231407e-01, 6.82768593e-01],
       [9.77839557e-01, 2.21604430e-02],
       [1.41938893e-01, 8.58061107e-01],
       [2.21648958e-01, 7.78351042e-01],
       [7.82053426e-01, 2.17946574e-01],
       [5.89092836e-02, 9.41090716e-01],
       [1.03925381e-01, 8.96074619e-01],
       [9.98569457e-01, 1.43054344e-03],
       [7.09332378e-01, 2.90667622e-01],
       [7.742170

In [82]:
model_ga = bentoml.sklearn.load_model("my_beautiful_model:4l3xsua4pgmnyvhb")
ba = model_ga.predict_proba(input_data)
ba

array([[9.87126398e-01, 1.28736024e-02],
       [2.24421330e-02, 9.77557867e-01],
       [1.39404621e-02, 9.86059538e-01],
       [6.88028578e-03, 9.93119714e-01],
       [9.48121581e-01, 5.18784188e-02],
       [5.35926939e-01, 4.64073061e-01],
       [9.29163302e-02, 9.07083670e-01],
       [8.37159015e-01, 1.62840985e-01],
       [7.44406044e-01, 2.55593956e-01],
       [3.49855566e-02, 9.65014443e-01],
       [5.36445024e-01, 4.63554976e-01],
       [9.82599687e-01, 1.74003131e-02],
       [1.62881648e-01, 8.37118352e-01],
       [9.87398877e-01, 1.26011228e-02],
       [1.66212859e-02, 9.83378714e-01],
       [3.17231407e-01, 6.82768593e-01],
       [9.77839557e-01, 2.21604430e-02],
       [1.41938893e-01, 8.58061107e-01],
       [2.21648958e-01, 7.78351042e-01],
       [7.82053426e-01, 2.17946574e-01],
       [5.89092836e-02, 9.41090716e-01],
       [1.03925381e-01, 8.96074619e-01],
       [9.98569457e-01, 1.43054344e-03],
       [7.09332378e-01, 2.90667622e-01],
       [7.742170